### ISSUE TITLE
Release 2.27 checklist

### ISSUE THREAD

**Issue by rok-cesnovar** [stan-dev/cmdstan#1005]
Here is the checklist for the next release.

**Feature freeze (May 20th):**
- [x] Create a release candidate tarball. Make sure RC has the new CMDSTAN_VERSION and that RC tarballs have binaries.
- [x] Create Math/Stan RC releases. Make sure versions are updated.
- [x] Create Stanc3 RC binary. Make sure versions are updated.
- [x] Create a release candidate feature/bugfix list (this doesn't need to be polished, just so that RC testers know what to test)
- [x] Run CmdstanR tests with the RC tarball (https://github.com/stan-dev/cmdstanr/runs/2628065416)
- [x] Make a Discourse RC post
- [x] Make a Twitter RC announcement

**Release (~May 27th~ TBD see https://github.com/stan-dev/cmdstan/issues/1005#issuecomment-847643702):**
- [x] Create the Math Release notes
- [x] Create the Stan Release notes
- [x] Create the Cmdstan Release notes
- [x] Create the Stanc3 Release notes
- [x] Create the Math release
- [x] Create the Stan release
- [x] Create the Stanc3 release
- [x] Create the CmdStan binaries (make sure the version is incremented and tarball includes binaries)
- [x] Run CmdStanR tests with the release tarball
- [x] Make a Discourse release announcement post
- [x] Cross-post the Discourse announcement on the Stan blog (dont forget thanking our sponsors)
- [x] Make the Twitter announcement

**Comment by rok-cesnovar** [comment]
Larger projects currently in the last phases:
- varmat
- adjoint ODE

**Comment by wds15** [comment]
Are we on track with things? Adjoint ODE looks as if it just makes the deadline... should there be any additional hickup it would be worthwhile to finish last cleanups for adjoint ODE (should there be any need).

**Comment by rok-cesnovar** [comment]
Its starting to look like varmat might be pushed to the next release again. Other things are on track for the freeze.

I have two minor PRs that I would like to get in (https://github.com/stan-dev/cmdstan/pull/1009, https://github.com/stan-dev/cmdstan/pull/1010), but these are not worth delaying anything for.

**Comment by mitzimorris** [comment]
I've got a branch for https://github.com/stan-dev/cmdstan/issues/1011 - if I got a PR in today, would that go in?

**Comment by wds15** [comment]
the freeze is on the 17th end of day anywhere.. so it's the 18th...

So if the PR can be reviewed by tomorrow then it can be in.

**Comment by rok-cesnovar** [comment]
Its end of day on the 18th, thats how we usually do it.

**Comment by wds15** [comment]
Even better

**Comment by wds15** [comment]
What's the matter with varmat?

When you post the RC can you point people to the design doc of the adjoint ODE thing? This is to make it possible for people to call the new function for which I am writing the doc this week... or do you have other suggestions?

Thanks!

**Comment by rok-cesnovar** [comment]
> What's the matter with varmat?

Missing stanc3 implementation, mostly ran out of time.

> When you post the RC can you point people to the design doc of the adjoint ODE thing? 

That was my plan yes!

**Comment by mitzimorris** [comment]
if anyone has time and feels qualified to review CmdStan pr https://github.com/stan-dev/cmdstan/pull/1017, that would be great.

**Comment by rok-cesnovar** [comment]
@serban-nicusor-toptal let me know when you have time to proceed with the release candidate. We only need to wait for this master stanc3 run to finish: https://jenkins.mc-stan.org/blue/organizations/jenkins/stanc3/detail/master/839/pipeline which should be soon.

**Comment by serban-nicusor-toptal** [comment]
Hey @rok-cesnovar I can start today around 5 PM CEST time.

**Comment by rok-cesnovar** [comment]
Great, thanks! If you can handle the first three points above it would be great! 
- Create a release candidate tarball. Make sure RC has the new CMDSTAN_VERSION and that RC tarballs have binaries.
- Create Math/Stan RC releases. Make sure versions are updated.
- Create Stanc3 RC binary. Make sure versions are updated.

I have the rest of the stuff ready and will check the tarballs/releases once they are ready.

**Comment by serban-nicusor-toptal** [comment]
Hey @rok-cesnovar here you can find the rcs:
- [math](https://github.com/stan-dev/math/releases/tag/v4.1.0-rc1)
- [stan](https://github.com/stan-dev/stan/releases/tag/v2.27.0-rc1)
- [cmdstan](https://github.com/stan-dev/cmdstan/releases/tag/v2.27.0-rc1)
- [stanc3](https://github.com/stan-dev/stanc3/releases/tag/v2.27.0-rc1)

It's taking a bit more because I am trying to figure out why [this jenkins job](https://jenkins.mc-stan.org/blue/organizations/jenkins/stanc3/detail/v2.27.0-rc1/3/pipeline/82/) is failing in the `Build & test static Windows binary` step.

```+ dune build -x windows

Error: ocamlfind toolchain windows isn't defined in

/usr/local/opam/4.07.0/lib/findlib.conf.d (context: default.windows)

script returned exit code 1```

**Comment by serban-nicusor-toptal** [comment]
I see, I will restart one more and see what happens. In the meanwhile I'll try to debug locally, maybe they changed something that affects us as we didn't change anything code wise afaik.

**Comment by serban-nicusor-toptal** [comment]
Sadly I'm getting the same error locally

**Comment by rok-cesnovar** [comment]
Weird, not sure what changed. Will take a look in the morning.

**Comment by serban-nicusor-toptal** [comment]
I've found that [here](https://github.com/stan-dev/stanc3/blob/163bcb1450d3b67f01f2254906786a7c39f69386/scripts/install_build_deps_windows.sh#L16) we're missing a `-y` which messes up the dependencies, I will update master and re-create the release, it worked fine locally so I expect it to work in Jenkins too.
I will create the tarball and tag you when done so you can review when you're available, no rush.

**Comment by rok-cesnovar** [comment]
Great. Fingers crossed. If you have time to build the cmdstan tarball today I can test and make an annoucement in the morning.

**Comment by serban-nicusor-toptal** [comment]
Everything seems to be alright now, weird how that error got into the pipeline and actually worked until now. 
Added tarball to cmdstan release: https://github.com/stan-dev/cmdstan/releases/tag/v2.27.0-rc1

**Comment by rok-cesnovar** [comment]
Thanks Nic! The release candidates are ready and all announcements have been posted. If all goes well the release will be next Thursday.

**Comment by rok-cesnovar** [comment]
Both Mac machines that are located at Columbia have gone offline yesterday. These Mac machines have been the most stable for the last few years and both of them going offline in the same day is very strange. Not much tests have run since the freeze so its very very unlikey this would be related to overload or anything like that.

We need these machines to build binaries for Mac and if we are unable to bring them online until Thursday, we will move the release to at least Monday (31st May). They will probably require physical intervention so not sure on the timeline to resolve this.

We could use the AWS Mac instances temporarily but that would mean that the minimum Mac version for CmdStan would be `macOS Mojave` (the oldest version we can get on AWS - a binary built on MacOS version X only work on version X and higher). This is more likely than not a non-problem, but would still like to avoid adding this restriction.

**Comment by rok-cesnovar** [comment]
We also need to resolve https://github.com/stan-dev/math/issues/2493 prior to that. But I think that should be resolved prior to Thursday.

**Comment by mitzimorris** [comment]
I have access to Columbia, so I could go up there today and try to figure this out.

**Comment by rok-cesnovar** [comment]
Great! @serban-nicusor-toptal what would need to be done with the machine? Just reboot I am guessing?

**Comment by serban-nicusor-toptal** [comment]
Awesome!
Just try to reboot, make sure they're online and if possible get their IPv4 so I can try to connect to them.
If the linux/win machines are there too, it's worth checking them out too.

Thanks !!

**Comment by rok-cesnovar** [comment]
@bgoodri  mentioned that the Mac machines are in Andrew's office right? The Linux/Windows are in Ben's office I believe so thats probably not accessible? 

The Macs are definitely a bigger priority. The machines are named `gelman-group-mac` and `old-imac`, not sure if that helps identifying them.

**Comment by mitzimorris** [comment]
that sounds about right.   one Mac machine is in my office (`gelman-group-mac`?) and the other is in Andrew's.
I might be able to get access to Ben's office, which is in a different building, depending on whether or not any of the admin staff in that building are back to working on campus.

**Comment by mitzimorris** [comment]
will be up there after 1pm EDT

**Comment by mitzimorris** [comment]
hi @rok-cesnovar and @serban-nicusor-toptal - I just rebooted both machines about 5 minutes ago - can you see them?

**Comment by rok-cesnovar** [comment]
@serban-nicusor-toptal jenkins doesnt see them, but not sure if that is relevant. Can you log on to them directly?

**Comment by serban-nicusor-toptal** [comment]
Hey they're online and we don't need to do anything else.
Thank you both for the help!

**Comment by mitzimorris** [comment]
is `old-imac` still running?

**Comment by mitzimorris** [comment]
hi @serban-nicusor-toptal - if I go up to Columbia tomorrow and put the machine back online, will you be able to change settings so that it doesn't go offline?  we're talking about that round black mac server.  there's no monitor or keyboard hooked up and I don't have a login (I don't think).

**Comment by rok-cesnovar** [comment]
Yeah, old-imac is still running.

**Comment by serban-nicusor-toptal** [comment]
Hey sorry I was AFK.
As rok said that one is still working.
We can try that @mitzimorris but it's just a hunch of mine not sure that's our case. I fear to not be a hardware issue, overheating or something like that that just triggered randomly now.

**Comment by wds15** [comment]
Are we going to fix the regression before release? I don‘t mind releasing if this is the only model affected, but I would expect that more models are being slow-down…it‘s just that it seems very hard to fix, 2.27 has a great lot to offer and we can still work on it… though my preference would be to get it fixed first (if we have a realistic chance to get it done in finite time).

**Comment by rok-cesnovar** [comment]
> Are we going to fix the regression before release? 

I would say we fix the regression or at least get more info before we release. I will have time to dig into it tomorrow.

**Comment by mitzimorris** [comment]
> We can try that @mitzimorris but it's just a hunch of mine not sure that's our case. I fear to not be a hardware issue, overheating or something like that that just triggered randomly now.

understood - machine is ancient.  but first failure was because it was unplugged, so maybe something got reset?

**Comment by rok-cesnovar** [comment]
Due to the issues with the Mac computer and the performance regression we still haven't gotten to the bottom of, I propose moving the release to Monday. We are unlikely to figure the regression today and I dont want to release on a Friday.

**Comment by rok-cesnovar** [comment]
@serban-nicusor-toptal I think we will need to set up that AWS Mac instance for the release. The performance regression was identified and we will need the Mac instance for the bugfix tests as well as the release.

**Comment by serban-nicusor-toptal** [comment]
Hey @rok-cesnovar I can work on it tomorrow hoping to be ready until Monday, but just FYI Mac instances on AWS can't be bought using Spot Requests and also we can't have it on-demand as it's treated as a bare metal so we'll need to run it 24/7 with a 24-hour minimum allocation period. [source](https://aws.amazon.com/ec2/instance-types/mac/)
@mitzimorris hey, are you still planning in revisiting Columbia these days ? No rush in doing so just checking before I start on the AWS stuff.

**Comment by mitzimorris** [comment]
hi @serban-nicusor-toptal,  I can only get access to Andrew's office Tues and Thurs.   I couldn't get up the this past Thursday, but will go up on Tuesday and will get access, one way or another.

**Comment by serban-nicusor-toptal** [comment]
Ah okay then we'll need to go for aws for sure until then. Thanks!

**Comment by serban-nicusor-toptal** [comment]
Hey @rok-cesnovar the new AWS Mac is up and running, I hope to get all the dependencies right.
Also FYI I couldn't find llvm@6 so I've installed and using llvm@7 if that's okay, if it's not we'll need to install the older version somehow ( it's not in brew ).
Also there are some jobs that will get stuck in the queue as we don't have a GPU attached to the AWS Mac, what should we do about these ?

Please let me know if you see any job failure so I can sort it out, thanks!

**Comment by rok-cesnovar** [comment]
We currently dont use the Mac+gpu combination, that label is not used in our tests anymore.

lets first wait for all tests to pass and merge the bugfix PRs. Its a holiday in the US today so no rush on releasing today.

**Comment by serban-nicusor-toptal** [comment]
Do we need [this pr](https://github.com/stan-dev/stan/pull/3043) for the current release ? Also, is there any other PR that we should wait for ?

**Comment by rok-cesnovar** [comment]
Yes, that is the last one we need to merge for the release.

**Comment by serban-nicusor-toptal** [comment]
Huh okay that's good to know, I see it has some test failures so I'll probably have to wait until that's fixed. Please let me know if there's anything else I can do for now.

**Comment by rok-cesnovar** [comment]
The PR was merged so we just need to wait for the develop tests to pass so it propagates to cmdstan. That should take 4-5 hours so I guess we are probably going to do it tomorrow?

To recap:
- stanc3 master is what we will release as 2.27.0 (no PRs were merged after RC)
- math develop is what we will release (1 Pr was merged so we need to regenerate for the release)
- stan develop is what we will release (Math submodule was updated + 1 PR was just merged)
- cmdstan (there was a PR merged + we need to wait for the submodule to be updated)

**Comment by serban-nicusor-toptal** [comment]
Nice, we can do it today too as I'll most probably work until late or leave it for tomorrow before US wakes up both work just fine for me. Thanks for the recap!

**Comment by mitzimorris** [comment]
@Serban Nicusor ***@***.***>  I am at Columbia now and will
be here until 3:30 pm New York time.
do you want to co-ordinate w/r/t restarting gelman-group-mac?

**Comment by serban-nicusor-toptal** [comment]
Hey, sure let's go for it I'm available.

**Comment by mitzimorris** [comment]
OK, I just rebooted the machine.  if you want to do a hangout, send invite
to my email.

**Comment by mitzimorris** [comment]
OK, I just rebooted the machine.  if you want to do a hangout, send invite to my email

**Comment by serban-nicusor-toptal** [comment]
I'm remotely connected to the machine, will try to see if I can change any setting for it.

**Comment by mitzimorris** [comment]
awesome.   it seems to be plugged into one of the wall ethernet connections.  took a photo and can reach out to CU IT if there's some kind of network issue.

**Comment by serban-nicusor-toptal** [comment]
I did change `pmset` settings to:
```
System-wide power settings:
 SleepDisabled          1
Active Profiles:
AC Power                -1*
Currently in use:
 standby              0
 Sleep On Power Button 1
 womp                 1
 autorestart          0
 hibernatefile        /var/vm/sleepimage
 powernap             0
 gpuswitch            2
 networkoversleep     0
 disksleep            0
 sleep                0
 autopoweroffdelay    14400
 hibernatemode        0
 autopoweroff         0
 ttyskeepawake        1
 displaysleep         10 (display sleep prevented by Bluetooth Setup Assistant)
 standbydelay         10800
```
To disable most of the sleep/turnoff so let's hope this fixed it.

Thanks a lot @mitzimorris !

**Comment by serban-nicusor-toptal** [comment]
Looks like we lost the mac machine again @mitzimorris. Nothing was running on it so we can rule out overheating I think also I don't think it was a standby/shutdown either as we changed those.

**Comment by mitzimorris** [comment]
OK,  I will reach out to CU IT.
cheers,
Mitzi

**Comment by wds15** [comment]
Do we have to sort out the Mac thing? Or can we proceed with different means?

**Comment by serban-nicusor-toptal** [comment]
Hey, I've already spin up a new Mac Instance on AWS that we can use for now.
I will start with the release in just a few moments!

**Comment by serban-nicusor-toptal** [comment]
Release is done but there's one thing left, to generate new docs and update release notes with the new urls.
I've tried to build [docs](https://github.com/stan-dev/docs) on Mac Mojave with R 3.3.3 and Ubuntu 20.04 with R 4.0.1 but it fails with the below error on both:

`python build.py 2 27`

```
Try to find the following text in _main.Rmd:
  \subitem {\tt (data row_ 
You may need to add $ $ around a certain inline R expression `r ` in _main.Rmd (see the above hint). See https://github.com/rstudio/rmarkdown/issues/385 for more info.
Error: LaTeX failed to compile _main.tex. See https://yihui.org/tinytex/r/#debugging for debugging tips. See _main.log for more info.
In addition: Warning message:
In normalizePath(dirname(f)) : path[1]="NA": No such file or directory
Execution halted
Command Rscript -e "bookdown::render_book('index.Rmd', output_format='bookdown::pdf_book')" failed
Traceback (most recent call last):
  File "build.py", line 113, in <module>
    main()
  File "build.py", line 109, in main
    make_docs(docspath, stan_version, doc, formats)
  File "build.py", line 47, in make_docs
    shexec(command)
  File "build.py", line 35, in shexec
    raise Exception(returncode)
Exception: 1
```

Not sure if I've messed something up in a dependency version or if it's a code error.

**Comment by mitzimorris** [comment]
tried to build the docs from current develop - failed on my mac. I don't think it's your scripts that are the problem here.
investigating.

**Comment by rok-cesnovar** [comment]
I have managed to find a solution, one of the tables failed to render (produces latex that doesnt compile).

Setting full_width to TRUE here fixes the issue: https://github.com/stan-dev/docs/blob/master/src/stan-users-guide/sparse-ragged.Rmd#L70

**Comment by serban-nicusor-toptal** [comment]
Nice! Good job for finding out the error.
Since this is a code change I've created a [PR](https://github.com/stan-dev/docs/pull/370) with your suggestion. Can you please review @mitzimorris and if alright merge? After that I'll generate the docs and post here.

**Comment by serban-nicusor-toptal** [comment]
Hey PR for docs can be found here https://github.com/stan-dev/docs/pull/371. 
https://stan-dev.github.io is also updated.
@rok-cesnovar I've also fixed the pipeline issues it had. It failed in `make manual` in cmdstan, there's not that function anymore.
I will shortly update release notes in github after docs are merged.

**Comment by serban-nicusor-toptal** [comment]
Done! Eveything seems to be in place now.
[Math v4.1.0](https://github.com/stan-dev/math/releases/tag/v4.1.0)
[Stan v2.27.0](https://github.com/stan-dev/stan/releases/tag/v2.27.0)
[CmdStan v2.27.0](https://github.com/stan-dev/cmdstan/releases/tag/v2.27.0)
[Stanc3 v2.27.0](https://github.com/stan-dev/stanc3/releases/tag/v2.27.0)

**Comment by rok-cesnovar** [comment]
Thanks Nic!

All of the announcements on various channels have now been posted so I am closing this issue. Thanks to all!

Next release is planned for the 27th of September (RC on the 20th).
