### ISSUE TITLE
Release 2.29.0 checklist

### ISSUE THREAD

**Issue by rok-cesnovar** [stan-dev/cmdstan#1073]
**Feature freeze (Februay 1st):**
- [x] Ensure all expiring language deprecations have been removed or given new removal dates.
- [x] Create and merge version updating pull requests in Math/Stan/Cmdstan. These should be the last PRs accepted before the freeze.
- [x] Create Math/Stan RC releases.
- [x] Create Stanc3 RC binary.
- [x] Create a release candidate tarball for x86. Make sure RC tarballs include stanc3 binaries.
- [x] Check external links in docs (i.e. TBB docs link)
- [x] Create a release candidate feature/bugfix list (major features/bugfixes that need testing, link to new docs in Github)
- [x] Run [CmdStanR tests](https://github.com/stan-dev/cmdstanr/actions/workflows/cmdstan-tarball-check.yaml) with the RC tarball.
- [x] Run CmdStanPy tests with the RC tarball.
- [x] Make a Discourse RC post.
- [x] Post a tweet with a link to the Discourse RC post.

**Release (February 14th - subject to change):**
- [x] Create the Math Release notes.
- [x] Create the Stan Release notes.
- [x] Create the Cmdstan Release notes.
- [x] Create the Stanc3 Release notes, include new deprecations and removals.
- [x] Rebuild and publish docs for the new version.
- [x] Check that docs for the previous release links correctly to the newest docs.
- [x] Create the Math release.
- [x] Create the Stan release.
- [x] Create the Stanc3 release.
- [x] Create x86 CmdStan tarballs (check version, check that the extracted folder is in the cmdstan-version format).
- [x] Create non-x86 CmdStan tarballs.
- [x] Run CmdStanR tests with the release tarball.
- [x] Make a Stan blog release announcement post (thank the sponsors and all contributors, mention new devs).
- [x] Link to the blog post in a Discourse thread.
- [x] Make a Twitter announcement.

**Comment by rok-cesnovar** [comment]
So if I am not missing anything, the only thing that we want to get into 2.29 and has not been merged yet is https://github.com/stan-dev/stan/pull/3095 by @SteveBronder, which squashes an unwanted behaviour we do not want to support going forward (it was only allowed for a version or 2) or have users assume its expected behaviour. 

Anything else I missed?

**Comment by rok-cesnovar** [comment]
> Ensure all expiring language deprecations have been removed or given new removal dates.

@WardBrian I guess for this release we can check this one since its the first time we are doing this?

> Create and merge version updating pull requests in Math/Stan/Cmdstan. These should be the last PRs accepted before the freeze.

@serban-nicusor-toptal we can start doing this now.

**Comment by WardBrian** [comment]
@rok-cesnovar yes correct. 2.32 will be the first time that’s required

**Comment by rok-cesnovar** [comment]
Per-PR release notes are now here: https://gist.github.com/rok-cesnovar/b7c2dbec22fc7cf88e102f924133a557#file-2_29_release_notes-txt

The Math/Stan/CmdStan are pretty straightforward as there was not much action. I would appreciate someone looking at those (no hurry - we dont need them for the RC, just comment on the gist with edits/fixes).

Version-updating PRs are now all approved, waiting for Math tests to pass then we can do the RC.

**Comment by serban-nicusor-toptal** [comment]
Release candidates, stanc3 binaries, the tarballs for x86 and non-x86 are now ready.

**Comment by rok-cesnovar** [comment]
Thanks @serban-nicusor-toptal.

I checked the external docs and am working on the list of features we will highlight in the RC post. @WardBrian can you run CmdStanPy tests whenever you have the chance?

**Comment by serban-nicusor-toptal** [comment]
CmdStanR failed on windows tests in [GH actions](https://github.com/stan-dev/cmdstanr/runs/5005058561?check_suite_focus=true)

**Comment by rok-cesnovar** [comment]
Ah, that is a CI issue, will fix shortly.

**Comment by serban-nicusor-toptal** [comment]
Good to know, thanks for the quick answer. Please let me know if there's anything else I can help with.

**Comment by WardBrian** [comment]
I've got some test failures in cmdstanpy but I think they're because we were assuming #1054 would be merged in this version. Investigating now

**Comment by WardBrian** [comment]
Uncovered some bugs in cmdstanpy, but after resolving those tests are green https://github.com/stan-dev/cmdstanpy/runs/5011314575

**Comment by rok-cesnovar** [comment]
Thanks. RC Annoucement will be up tomorrow.

**Comment by WardBrian** [comment]
Will we be pushing the release until the 14th?

**Comment by rok-cesnovar** [comment]
Yeah, fixed the dates in the top post. Thanks.

**Comment by rok-cesnovar** [comment]
The RC annoucement is [live](https://discourse.mc-stan.org/t/cmdstan-2-29-0-release-candidate/26182). Thanks @WardBrian  for the help. Also posted the link on Twitter. Hopefully, we get some testers. If all goes well the release will happen on Valentine's day :) 

I plan on running some performance tests in a couple of days.

**Comment by WardBrian** [comment]
@rok-cesnovar re: the 'check external links' bullet point, I found this very helpful tool: https://github.com/tcort/markdown-link-check

**Comment by rok-cesnovar** [comment]
Nice! added to the [checklist](https://github.com/stan-dev/ci-scripts/blob/master/release-scripts/checklist.md).

**Comment by WardBrian** [comment]
It produces some false alarms but did catch a few broken links I'm going to fix right now

**Comment by rok-cesnovar** [comment]
@serban-nicusor-toptal when you have the chance, please make RC2 for stanc3 and cmdstan. Thanks!

**Comment by serban-nicusor-toptal** [comment]
stanc3 [v2.29.0-rc2](https://github.com/stan-dev/stanc3/releases/tag/v2.29.0-rc2) and cmdstan [v2.29.0-rc2](https://github.com/stan-dev/cmdstan/releases/tag/v2.29.0-rc2) are now up!

**Comment by WardBrian** [comment]
https://github.com/stan-dev/cmdstan/issues/1076 seems both simple enough and important enough that we should get it in before release, right?

**Comment by WardBrian** [comment]
There are a few docs issues I think would be great to address before the release (not necessarily blocking, though):

https://github.com/stan-dev/docs/issues/487

https://github.com/stan-dev/docs/issues/482

https://github.com/stan-dev/docs/issues/466

**Comment by rok-cesnovar** [comment]
I am working on https://github.com/stan-dev/docs/issues/466 Should have something ready over the weekend and for review on Monday.

**Comment by rok-cesnovar** [comment]
I fell into a different rabbit hole so I am not going to be able to close https://github.com/stan-dev/docs/issues/466 before the release but will work on finishing that this week. Its not something we need to reference in release notes so not critical ATM.

@serban-nicusor-toptal There were no additional reports for the release candidate so we can go ahead and start the release process. For the release notes use the notes we used for the RC: https://gist.github.com/rok-cesnovar/b7c2dbec22fc7cf88e102f924133a557

@WardBrian Do we wait for https://github.com/stan-dev/docs/pull/455 before we rebuild the docs? Or should we just go ahead and do it?

**Comment by WardBrian** [comment]
No need to wait imo, will just be in the next release

**Comment by serban-nicusor-toptal** [comment]
We've released stanc3 again after a quick patch before the release and we're now waiting for the stanc3 binaries build so I can add them to cmdstan and release it too. ETA ~1h
Thank @rok-cesnovar for building the docs, PRs for [docs](https://github.com/stan-dev/docs/pull/489) and [stan-dev.github.io](https://github.com/stan-dev/stan-dev.github.io/pull/163) are ready for review and merge.

**Comment by serban-nicusor-toptal** [comment]
The release is now officially out!

- [math v4.3.0](https://github.com/stan-dev/math/releases/tag/v4.3.0)
- [stan v2.29.0](https://github.com/stan-dev/stan/releases/tag/v2.29.0)
- [cmdstan v2.29.0](https://github.com/stan-dev/cmdstan/releases/tag/v2.29.0)
- [stanc3 v2.29.0](https://github.com/stan-dev/stanc3/releases/tag/v2.29.0)

**Comment by WardBrian** [comment]
@serban-nicusor-toptal If I go ahead and build collab-cmdstan-2.29 can I upload that tarball directly to the release?

**Comment by serban-nicusor-toptal** [comment]
Yes @WardBrian 
If we need it every release I can add building collab to the release process so we can do it every time just need an example on how you're generating it.

**Comment by WardBrian** [comment]
The process is unfortunately very manual - see this forum post https://discourse.mc-stan.org/t/planning-the-2-29-release/25711/26

The collab version is essentially just the linux targz but pre-compiled to run on the collab instances. The last time we had one was 2.23, so I'm not sure how in-demand they are

**Comment by serban-nicusor-toptal** [comment]
Just checked manuals and docs, they're looking great and links are working fine. 
Thanks a lot, @rok-cesnovar and @WardBrian for helping out!

---

I took a look at the collab instructions Mitzi wrote, it's something I don't mind doing every release if there's anyone there using cmdstanpy on collab. Will try it now to see how it goes and I'll start doing it from next release if that's okay with you @WardBrian

**Comment by WardBrian** [comment]
@serban-nicusor-toptal I think it might be worth doing. I've done it for this release. 

I'm not sure how many collab users we have, or if conda would be a viable alternative for them. @mitzimorris - do you know if Collab can install conda packages?

**Comment by WardBrian** [comment]
colab-cmdstan-2.23.0.tar.gz was downloaded 2253 times over the past 2 years. So as a percentage it's quite small, but it is certainly getting used

**Comment by WardBrian** [comment]
Running cmdstanpy tests again for good measure: https://github.com/stan-dev/cmdstanpy/runs/5190682001

Thanks @rok-cesnovar @serban-nicusor-toptal

**Comment by serban-nicusor-toptal** [comment]
That's more than enough to make it worth it!

I gave the script a try and made a small, quick version for myself to use from now on, it's using [transfer.sh](https://github.com/dutchcoders/transfer.sh) to upload the archive so we can skip the GCloud step.
```
#!/bin/bash

CURRENT_VERSION=2.29.0

# cleanup existing cmdstan installs, as needed
!if [ -e $HOME/.cmdstan ] ; then echo "cleanup"; rm -rf $HOME/.cmdstan; fi

# install cmdstanpy
!pip install --upgrade cmdstanpy
from cmdstanpy import install_cmdstan
install_cmdstan()

# Create tgz
!ls -a $HOME/.cmdstan        # expecting default cmdstan install here
!cd $HOME/.cmdstan; tar -cf - cmdstan-$CURRENT_VERSION | gzip > $HOME/cmdstan-$CURRENT_VERSION.tgz
!tar -tzf $HOME/cmdstan-$CURRENT_VERSION.tgz | head

# Use transfer.sh to upload our achive for easy retrieval
!curl --upload-file /root/cmdstan-$CURRENT_VERSION.tgz https://transfer.sh/cmdstan-$CURRENT_VERSION.tgz

```

**Comment by rok-cesnovar** [comment]
Announcements posted.

Thanks to everyone that helped out, especially Brian and Nic! On to the next one :)
