### ISSUE TITLE
2.26 release varmat meta-issue

### ISSUE THREAD

**Issue by bbbales2** [stan-dev/cmdstan#958]
#### Summary:

This issue is to track what is yet to be done for varmat to go out in 2.26. Edit at will!

I will try to keep it updated with what I know about:

- Stanc3 https://github.com/stan-dev/stanc3/pull/755
  - [ ] Create a list of function signatures in Math that support `varmat` arguments. Work in progress [here](https://github.com/stan-dev/cmdstan/issues/958#issuecomment-757504441)
  - [x] Figure out a language implementation - A version of the compiler that makes a variable a varmat if the name ends in `_varmat` is available [here](https://github.com/stan-dev/stanc3/pull/755#issuecomment-740670144)
    - [x] Finish the language parts of the design doc. Finished design doc [here](https://github.com/stan-dev/design-docs/blob/master/designs/0005-static-matrices.md)
    - [x] scalar read/writes of `varmat` variables might be slow (it's come up when we talk implementation). Results [here](https://github.com/stan-dev/design-docs/pull/29#issuecomment-746870561)
- Math
  - [x] Finish the `varmat` parts of the design doc. Finished design doc [here](https://github.com/stan-dev/design-docs/blob/master/designs/0005-static-matrices.md)
  - [ ] Document `varmat` at the C++ level, from the perspective of someone coming to Math to write a function. This is higher level than Doxygen and lower level than Stan user docs.
  - [ ] Update all distributions to work with `varmat`
    - [ ] Non-multivariate distributions. Work in progress [here](https://github.com/stan-dev/math/pull/2278) and [here](https://github.com/stan-dev/math/pull/2214)
    - [ ] Multivariate distributions. Work in progress [here](https://github.com/stan-dev/math/pull/2284) and [here](https://github.com/stan-dev/math/pull/2266)
  - [ ] Write `varmat` implementations for every function that had custom `matvar` autodiff, work in progress [here](https://github.com/stan-dev/math/issues/2101)
  - [ ] Write `varmat` implementations for all the functions used in the [constrain functions](https://mc-stan.org/docs/2_25/reference-manual/variable-transforms-chapter.html). 
    - [x] Matrix constrains [here](https://github.com/stan-dev/math/pull/2254)
    - [ ] Upper/lower bounds[here](https://github.com/stan-dev/math/pull/2285)

#### Current Version:
v2.25.0

**Comment by bbbales2** [comment]
Writing this list is making me think that the Math implementation of `varmat` is done in the sense that `varmat` is a type and exists, and any deficiencies in the `varmat` implementation can be worked around at the compiler level.

To some extent, the limitation of `varmat` math is that it doesn't support all functions, and that will also be true in 6 weeks (it's unrealistic to convert everything).

I suspect it will make the compiler implementation simpler if we can do all the constrain functions with varmats, but for everything else it all goes back to the list of what functions are done?

So maybe the big to-do for varmat is something like is available for expressions? If we had a script that says, for every function signature available to the stanc3 compiler, does varmat compile all the possible signatures, then we'd be done? With that list, then the stanc3 compiler would know how to use everything.

**Comment by bbbales2** [comment]
Also would such a thing work for OpenCL? Is the assumption "if it compiles, then we can use it" good? It's not necessarily true, and I guess we could accidentally write functions at the Stan Math level that accidentally work but have bugs, so maybe that's no good.

**Comment by rok-cesnovar** [comment]
> So maybe the big to-do for varmat is something like is available for expressions?

Yeah, I think something similar should be done. Not sure at this moment if it needs to be run on PRs, but yes, something like that where we shorten the list of signatures that don't support it. In the long term this may not be required if we decide that we will go varmat-only.

> Also would such a thing work for OpenCL? Is the assumption "if it compiles, then we can use it" good? 

Unfortunately no, for OpenCL we also need to remove any signatures for which we know we will never be faster with Opencl, from the list. That will be done using the benchmark @t4c1 is working on.

**Comment by bbbales2** [comment]
> something like that where we shorten the list of signatures that don't support it.

Yeah I guess this is the same as expressions. We should do the testing in math and make part of the merging be removing it from the unsupported list.

> Unfortunately no, for OpenCL we also need to remove any signatures for which we know we will never be faster with Opencl, from the list.

Oh I see. Oh well.

> That will be done using the benchmark @t4c1 is working on.

Oh okay. Is OpenCL compiler implementation similar to the varmat plan where we'd just turn on varmats, use them as much as possible, and convert to and from matvar types automatically as needed?

**Comment by rok-cesnovar** [comment]
>  Is OpenCL compiler implementation similar

Yes, it is somewhat similar. 

It's working with distributions only (a distribution is simple to support because the return type is a scalar (and thus in the global memory of the CPU, not OpenCL device). For cases where the return type is not a scalar, we are still working it out. We are being very defensive with the Stanc3 implementation where we rather miss a speedup opportunity or two if it means a simpler and less "dangerous" stanc3 implementation.

**Comment by bbbales2** [comment]
> For cases where the return type is not a scalar, we are still working it out.

Oh okay, that makes sense.

For varmat, do you know of any blockers in the Math library? Like the existing implementation is sort of a proof of concept that what is there now works with all the tricky parts of Stan (IO and interface and whatnot). If Math library development stopped today, we could have a functioning (if limited) `varmat` release still, right?

So stanc3 is the critical path there, and then there are quality of life things to do in Math that will make everything better.

**Comment by rok-cesnovar** [comment]
> If Math library development stopped today, we could have a functioning (if limited) varmat release still, right?

Based on working with the preliminary stanc3 version I would say yes. It's now mostly a matter of which functions we support and how we are going to handle stanc3.

**Comment by avehtari** [comment]
> To some extent, the limitation of varmat math is that it doesn't support all functions, and that will also be true in 6 weeks (it's unrealistic to convert everything).

Can you clarify the consequences if there is release with mix of supported and non-supported? For example, the good case is that the supported ones just happen to be faster/better, and the bad case is that there will be extra trouble for users until all are supported.

**Comment by bbbales2** [comment]
> Can you clarify the consequences if there is release with mix of supported and non-supported?

This will be a function of the language implementation. In the original use case we were doing explicit types, in which case as we add more varmat functions the user would have to look up what is supported and update their code.

Now we're proposing something more automatic, where the compiler somehow decides whether to use varmats and matvars. The updated design doc will be up soon so we can talk through this (draft is here: https://github.com/stan-dev/design-docs/pull/29, info at the end).

**Comment by rok-cesnovar** [comment]
> `fma` function might be needed too

The only stanc3 signature for fma is `real fma(real, real, real)` so I am not sure this is needed. The prim and rev implementations in Stan Math also only support scalars.

**Comment by SteveBronder** [comment]
No it's not needed.

**Comment by rok-cesnovar** [comment]
Cool, removed it from the checklist then.

**Comment by bbbales2** [comment]
@rok-cesnovar Signature lists in!

I have the signatures broken into three groupings, compatible, incompatible, and impossible.

Compatible signatures are the ones that can compile with at least one varmat argument.

Incompatible signatures are the ones that could conceivably compile with at least one varmat argument, but fail to.

Impossible signatures are ones that do not take varmat inputs.

[compatible.txt](https://github.com/stan-dev/cmdstan/files/5792915/compatible.txt)
[incompatible.txt](https://github.com/stan-dev/cmdstan/files/5792916/incompatible.txt)
[impossible.txt](https://github.com/stan-dev/cmdstan/files/5792917/impossible.txt)

These are formatted like the output of the stanc dump command.

To make it easier to skim, I also have lists of only the function names. In this case, it's possible for a function to appear in two lists (`real mean(vector)` is incompatible and `real mean(real[])` is impossible so `mean` appears in two lists).

[compatible_names.txt](https://github.com/stan-dev/cmdstan/files/5792919/compatible_names.txt)
[incompatible_names.txt](https://github.com/stan-dev/cmdstan/files/5792921/incompatible_names.txt)
[impossible_names.txt](https://github.com/stan-dev/cmdstan/files/5792922/impossible_names.txt)

Questions are:
1. Is this a suitable format for the function signatures?
2. Do you see any obvious problems with the results?

I'll work on cleaning up the script and opening a pull req. in Math so we can automate this in the future (it's currently a kinda messy thing based off Tadej's benchmarks). I'm not gonna worry about having this automation done for this release tho.

**Comment by bbbales2** [comment]
Oh yeah just for a head count, it's about 10k compatible signatures, 11k incompatible ones, and 5k impossible.

There are 205 functions in the compatible names list, and 332 in the incompatible names list and 523 if I put those together and look for uniques (so there's only 14 functions in both lists -- assuming I did my bash commands right).

**Comment by bbbales2** [comment]
There could be functions in this list that compile with varmat but have not been tested. These would be things that are just templated very generically, for instance.

**Comment by bbbales2** [comment]
For future reference here are the functions with both compatible and incompatible signatures:

```
beta_proportion_log
beta_proportion_lpdf
gp_exp_quad_cov
gp_matern52_cov
head
log_mix
multiply_log
ordered_constrain
positive_ordered_constrain
reverse
segment
simplex_constrain
tail
unit_vector_constrain
```

**Comment by bbbales2** [comment]
I had a closer look at this.

```
unit_vector_constrain
ordered_constrain
positive_ordered_constrain
```

are actually compatible with varmat and this test is failing because it's testing signatures that shouldn't be called. These are weird functions because they increment lp values that optionally get passed in (and these have to match the return type of the rest of the arguments -- can't be double if the rest of the arguments are var)

**Comment by bbbales2** [comment]
@rok-cesnovar Here is the fully compatible list of varmat functions: 
[compatible_names.txt](https://github.com/stan-dev/cmdstan/files/5797026/compatible_names.txt)

All these functions, fully support varmat signatures (all vector/matrix arguments that potentially could be written as varmats, support it).

**Comment by bbbales2** [comment]
I'm gonna close this since it's not a 2.26 thing. Should be easy to find if we need the info out of it.
