### ISSUE TITLE
2.26 release OpenCL support meta-issue

### ISSUE THREAD

**Issue by rok-cesnovar** [stan-dev/cmdstan#959]
#### Summary:

This issue is to track what is yet to be done for OpenCL support in 2.26.

- [x] extend the kernel generator to enable adding support for most distributions

@t4c1 did a ton of work here. The k.g. has been extended so that a lot of distributions have already been implemented with it. See "Supported distributions" in http://mc-stan.org/math/opencl_support.html

- [x] add support for simpler distributions (`_lpmf`/`_lpdf` functions only) 

See "Supported distributions" in http://mc-stan.org/math/opencl_support.html 
Again, a huge effort by Tadej. We may add additional ones, but even supporting the listed ones will be a huge improvement.

- [x] create the script to create OpenCL vs CPU benchmarks on-the-fly (#2260)

Tadej mentioned that this is close to being ready. This will help us in the future as well.

- [x] run the benchmarks to identify distribution signatures that make sense to use with OpenCL

Most importantly, we need to flag the signatures for which the data transfer time is larger than the runtime on CPU. Those are obviously never going to be faster on the GPU.

- [x] add support for OpenCL supported distributions to stanc3

A PR for that is open, we just need to eliminate signatures that will be flagged by the benchmarks. https://github.com/stan-dev/stanc3/pull/754 

- ~implement stanc3 support for functions not returning scalars~

The first part will implement support for distributions, because for those, the return type is a scalar which will be returned to the CPU always. For cases like `matrix multiply(matrix, matrix)` its a bit more involved whether we need to return the result to the CPU or not. This is still in the works and may require a design doc.
We will add all functions that support both the prim and rev versions. A list of supported functions is given here: https://github.com/stan-dev/math/issues/1854

- [x] Add and test OpenCL CPU support with zero-copy

In progress: https://github.com/stan-dev/math/pull/2182 and https://github.com/stan-dev/math/pull/2219
Mostly ready, just hashing out issues with test setup.

- [ ] Add a OpenCL/GPU in Stan section/chapter to the user guide

Also clean up the rest of the function signatures docs (GLMs mainly) of GPU mentions. We want all OpenCL/GPU info in one place, not scattered around the documentation.

**Comment by wds15** [comment]
2.26 is becoming a huge release of all this stuff goes in(Opencl, expressions, varmat)!!!

**Comment by avehtari** [comment]
Looks good. Couple minor comments:

> Most importantly, we need to flag the signatures for which the data transfer time is larger than the runtime on CPU. Those are obviously never going to be faster on the GPU.

Never is a strong word. Are there any predictions how data transfer speeds develop in the future?

> add rev and prim support for more functions

If this is a checklist for checking when this project is ready to be included in a release, then "more" is unclear. Is there more specific target or is any number large than one ok?

**Comment by rok-cesnovar** [comment]
> Never is a strong word. Are there any predictions how data transfer speeds develop in the future?

Good call. Yeah transfers will definitely get faster over time with pci express 4 and 5. Also the addition of high-end Intel GPUs that have a unified memory with the CPU and the possibiluty of zero copy might also have an effect. Will modify.

> If this is a checklist for checking when this project is ready to be included in a release, then "more" is unclear. Is there more specific target or is any number large than one ok?

Good point. We want to have more, but we are already happy with what we currently have. Will change language here.

Also missed an inportant item: user guide/cmdstan sections.

**Comment by rok-cesnovar** [comment]
Update: 
- benchmarks for distributions were done. See https://github.com/rok-cesnovar/stan-math-opencl-benchmarks/blob/main/summaries/radeonvii_vs_i7_distributions.md and the entire repo https://github.com/rok-cesnovar/stan-math-opencl-benchmarks
- Stanc3 PR to add OpenCL support for additional distributions has been reviewed and should be merged today
- OpenCL CPU support with zero-copy has been merged and is enabled

The missing parts are enabling other functions (non-lpdf/lpmf) that do not return scalars in stanc3 and docs - Cmdstan/Stan guide (this will most likely have to wait for the freeze). I think we are on track here.

**Comment by rok-cesnovar** [comment]
>  implement stanc3 support for functions not returning scalars

This was not implemented for two reasons: we ran out of time for an near-optimal stanc3 version of this and a non-optimal one does not make much sense without varmat support which was abandoned for 2.26. I do still take the expanded distribution support as a huge win. The user-facing docs will be done during the freeze.
